version: '3'

services:
  db:
    image: 'postgres:11'
    container_name: 'java.postgres'
    environment:
      - 'POSTGRES_USER=Savage'
      - 'POSTGRES_PASSWORD=qwerty123'
      - 'POSTGRES_DB=piranha'
    ports:
      - '5432:5432'

  app:
    build: ./
    container_name: 'catalog-app'
    depends_on:
      - 'db'
    ports:
      - '8080:8080'
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db/piranha
        - SPRING_DATASOURCE_USERNAME=Savage
        - SPRING_DATASOURCE_PASSWORD=qwerty123
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        - SPRING_JPA_HIBERNATE_GLOBALLY_QUOTED_IDENTIFIERS=true
        - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
        - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect